import { useState } from 'react'
import { dateKey, daysLeft, deadlineState, deadlineText, formatDate, habitCompletedOn, isHabitScheduled, sortMilestones } from '../data'
import HabitRow from '../components/HabitRow'
const todayLabel=value=>new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date(`${value}T00:00:00`))
export default function Home({goals,milestones,habits,habitRecords,onToggleHabit,onOpenGoal,onAddHabit}){
 const[expanded,setExpanded]=useState([]),today=dateKey(),todayHabits=habits.filter(h=>isHabitScheduled(h,today)||habitCompletedOn(habitRecords,h.id,today)),done=todayHabits.filter(h=>habitCompletedOn(habitRecords,h.id,today)).length,allDone=todayHabits.length>0&&done===todayHabits.length
 const toggle=id=>setExpanded(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])
 return <div className="page home-page"><header className="today-header"><p>{todayLabel(today)}</p><h1>{allDone?'今日の一歩、完了です ✦':'今日も一歩ずつ進めよう'}</h1></header><section className={'today-panel '+(allDone?'celebration':'')}><div className="section-heading"><div><span className="eyebrow">TODAY</span><h2>今日の継続行動</h2></div><div className="today-score"><strong>{done} / {todayHabits.length}</strong><span>完了</span></div></div>{allDone&&<p className="celebration-message">すべて達成。積み重ねがまたひとつ増えました。</p>}{todayHabits.length?<div className="habit-list">{todayHabits.map(h=><HabitRow key={h.id} habit={h} records={habitRecords} day={today} onToggle={onToggleHabit}/>)}</div>:<div className="empty">今日の行動はありません。</div>}<button className="text-button" onClick={onAddHabit}>＋ 継続行動を追加</button></section><section className="section goals-section"><div className="section-heading"><div><span className="eyebrow">GOALS</span><h2>進行中の目標</h2></div></div><div className="goal-list">{goals.map(g=>{const all=milestones.filter(m=>m.goalId===g.id),complete=all.filter(m=>m.completedAt).length,open=sortMilestones(all.filter(m=>!m.completedAt)),isOpen=expanded.includes(g.id),visible=open.slice(0,isOpen?3:1),hidden=Math.max(0,open.length-visible.length),left=daysLeft(g.deadline);return <article className="goal-card" key={g.id}><button className="goal-card-main" onClick={()=>onOpenGoal(g.id)}><div className="goal-card-top"><div><span className="goal-label">目標</span><h3>{g.title}</h3><small>{formatDate(g.deadline)}まで</small></div><span>›</span></div><div className={'countdown goal-countdown '+deadlineState(left)}>{deadlineText(left)}</div><div className="goal-progress-count">小目標　<strong>{complete} / {all.length}</strong> 達成</div></button>{open.length?<div className="goal-milestones"><span className="next-label">次の小目標</span>{visible.map((m,i)=>{const ml=daysLeft(m.deadline);return <button className="goal-milestone-row" key={m.id} onClick={()=>onOpenGoal(g.id)}><span><i>{i+1}</i><strong>{m.content}</strong><small>{formatDate(m.deadline)}</small></span><b className={deadlineState(ml)}>{deadlineText(ml)}</b></button>})}{open.length>1&&<button className="expand-milestones" onClick={()=>toggle(g.id)}>{isOpen?'小目標を閉じる':`残り${open.length-1}件を見る`} <span>{isOpen?'↑':'↓'}</span></button>}{isOpen&&hidden>0&&<button className="more-to-detail" onClick={()=>onOpenGoal(g.id)}>さらに{hidden}件を目標詳細で見る →</button>}</div>:<button className="all-achieved" onClick={()=>onOpenGoal(g.id)}>✦ すべての小目標を達成しました</button>}</article>})}{!goals.length&&<div className="empty">進行中の目標はありません。</div>}</div></section></div>
}
